"""Add item_group to Item model

Revision ID: 3e0d34c90d7b
Revises: 
Create Date: 2025-05-14 13:39:18.387650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e0d34c90d7b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_group', sa.String(length=50), nullable=True, server_default='Misc.'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('item_group')
    # ### end Alembic commands ###

